version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-devops
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock  # Mounts your project folder
    environment:
      - JENKINS_OPTS="--httpPort=8080"

volumes:
  jenkins_home:

